# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3


before_script:
  - pwd
  - which python
  - python -V
  - pip list
  - pip install .
  - pip list

stages:
  - test

unit tests:
  stage: test
  script:
    - python -m unit test/run_all_integration.py
